models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $name
 * @property int $parent_id
 * @property int|null $weight
 * @property string|null $description
 * @property string $alias
 * @property string|null $meta_description
 *
 * @property Article[] $articles
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'alex290\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public $imageFile;

    public function rules()
    {
        return [
            [['name', 'parent_id'], 'required'],
            [['parent_id', 'weight'], 'integer'],
            [['description'], 'string'],
            [['name', 'alias', 'meta_description'], 'string', 'max' => 255],
            [['imageFile'], 'file', 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'parent_id' => 'Родитель',
            'weight' => 'Вес',
            'description' => 'Описание',
            'alias' => 'URL',
            'meta_description' => 'Meta Description',
        ];
    }

    /**
     * Gets query for [[Articles]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Article::className(), ['category_id' => 'id']);
    }

    public function upload()
    {
        if ($this->validate()) {
            $path = 'upload/' . $this->imageFile->baseName . '.' . $this->imageFile->extension;
            $this->imageFile->saveAs($path);
            $this->attachImage($path);
            unlink($path);
            return true;
        } else {
            return false;
        }
    }
}

controllers/ArticleController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use yii\data\Pagination;
use yii\web\Controller;

class ArticleController extends Controller
{
    public function actionView($id)
    {
        $model = Article::findOne($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Category;
use yii\data\Pagination;
use yii\web\Controller;

class CategoryController extends Controller
{
    public function actionView($id)
    {
        $model = Category::findOne($id);

        $query = Article::find()->orderBy(['date_create' => SORT_ASC])->where(['category_id' => $id]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $articles = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('view', [
            'model' => $model,
            'articles' => $articles,
            'pages' => $pages,
        ]);
    }
}

views/category/view.php
<?php

use app\models\FrontText;
use yii\helpers\Url;

$path = str_replace("\\", "/", $model->getImage()->getPath());
// debug($path);

$this->title = $model->name;
?>
<header class="w-100 header-category d-flex justify-content-center align-items-center mb-5" style="background-image: url(/web/<?= $path ?>);">
    <div class="header-category-over"></div>
    <h1 class="text-center text-white position-relative"><?= $this->title ?></h1>
</header>
<div class="container pt-5 pb-5">
    <?php if ($articles != null) : ?>
        <div class="row">
            <?php foreach ($articles as $key => $article) : ?>
                <div class="col-12 col-md-4">
                    <a href="<?= Url::to(['/article/view', 'id' => $article->id]) ?>" class="card">
                        <img src="/web/<?= str_replace("\\", "/", $article->getImage()->getPath('600x400')); ?>" alt="" class="img-fluid">
                        <div class="card-body">
                            <h3 class="text-dark" style="font-size: 21px;"><?= $article->name ?></h3>
                            <p class="text-dark"><?= $article->body ?></p>
                        </div>
                    </a>
                </div>
            <?php endforeach ?>
        </div>
    <?php endif ?>
</div>